RunAction "Login", oneIteration
RunAction "Datos_Generales", oneIteration
RunAction "Contrato_Colaborador", oneIteration
RunAction "Exoneracion", oneIteration
RunAction "Amazonia", oneIteration
RunAction "Reorg", oneIteration
RunAction "Mineria", oneIteration
RunAction "PrincipalesSocios", oneIteration
RunAction "Alquileres", oneIteration
RunAction "Mermas", oneIteration
RunAction "Operaciones", oneIteration
RunAction "Regalias", oneIteration
RunAction "InformacionGeneral", oneIteration
RunAction "Desuso", oneIteration
RunAction "PerdidaExtraordinaria", oneIteration
RunAction "GastosRealizados", oneIteration
RunAction "IdentificacionVehiculos", oneIteration
RunAction "EmpresaConstructora", oneIteration
RunAction "GastosRepresentacion", oneIteration
RunAction "RentaInternacional", oneIteration
RunAction "GastosInvestigacion", oneIteration
RunAction "Determina_Activo", oneIteration
RunAction "Determina_Pasivo_Patrimonio", oneIteration
RunAction "EstadoResultados", oneIteration
RunAction "Determina_Mineria", oneIteration
